#+STARTUP: overview
#+STARTUP: hidestars
#+STARTUP: indent

* umbrella man
From the following [[http://www.theguardian.com/news/2013/oct/07/jfk-assassination-creepiest-detail-parkland][article]] on The Guardian. Who was that [[http://www.nytimes.com/video/2011/11/21/opinion/100000001183275/the-umbrella-man.html][man]] opening a large
black umbrella on a hot Dallas day?

* The End of Theory: The Data Deluge Makes the Scientific Method Obsolete
A superb [[http://www.wired.com/science/discoveries/magazine/16-07/pb_theory][article]] foreshadowing the end of modeling in scientific research and
the emergence of the agnostic Petabyte Age (Chris Anderson, Wired, 23Jun2008)

* the global burden of cancer
The Economist Graphic Detail blog from February 11, 2014, has an infographics on
global cancer incidence and mortality.
Link [[http://www.economist.com/blogs/graphicdetail/2014/02/daily-chart-6?fsrc%3Drss][here]].

* curse of dimensionality
From [[http://en.wikipedia.org/wiki/Curse_of_dimensionality][Wikipedia]]:

The curse of dimensionality refers to various phenomena that arise when
analyzing and organizing data in high-dimensional spaces (often with hundreds or
thousands of dimensions) that do not occur in low-dimensional settings such as
the three-dimensional physical space of everyday experience.  There are multiple
phenomena referred to by this name in domains such as numerical analysis,
sampling, combinatorics, machine learning, data mining and databases.  The
common theme of these problems is that when the dimensionality increases, the
volume of the space increases so fast that the available data becomes sparse.
This sparsity is problematic for any method that requires statistical
significance.  In order to obtain a statistically sound and reliable result, the
amount of data needed to support the result often grows exponentially with the
dimensionality.  Also organizing and searching data often relies on detecting
areas where objects form groups with similar properties; in high dimensional
data however all objects appear to be sparse and dissimilar in many ways which
prevents common data organization strategies from being efficient.  The term
curse of dimensionality was coined by Richard E. Bellman when considering
problems in dynamic optimization.
