#+STARTUP: overview
#+STARTUP: hidestars
#+STARTUP: indent

* umbrella man
From the following [[http://www.theguardian.com/news/2013/oct/07/jfk-assassination-creepiest-detail-parkland][article]] on The Guardian. Who was that [[http://www.nytimes.com/video/2011/11/21/opinion/100000001183275/the-umbrella-man.html][man]] opening a large
black umbrella on a hot Dallas day?

* The End of Theory: The Data Deluge Makes the Scientific Method Obsolete
A superb [[http://www.wired.com/science/discoveries/magazine/16-07/pb_theory][article]] foreshadowing the end of modeling in scientific research and
the emergence of the agnostic Petabyte Age (Chris Anderson, Wired, 23Jun2008)

* the global burden of cancer
The Economist Graphic Detail blog from February 11, 2014, has an infographics on
global cancer incidence and mortality.
Link [[http://www.economist.com/blogs/graphicdetail/2014/02/daily-chart-6?fsrc%3Drss][here]].

* curse of dimensionality
From [[http://en.wikipedia.org/wiki/Curse_of_dimensionality][Wikipedia]]:

The curse of dimensionality refers to various phenomena that arise when
analyzing and organizing data in high-dimensional spaces (often with hundreds or
thousands of dimensions) that do not occur in low-dimensional settings such as
the three-dimensional physical space of everyday experience.  There are multiple
phenomena referred to by this name in domains such as numerical analysis,
sampling, combinatorics, machine learning, data mining and databases.  The
common theme of these problems is that when the dimensionality increases, the
volume of the space increases so fast that the available data becomes sparse.
This sparsity is problematic for any method that requires statistical
significance.  In order to obtain a statistically sound and reliable result, the
amount of data needed to support the result often grows exponentially with the
dimensionality.  Also organizing and searching data often relies on detecting
areas where objects form groups with similar properties; in high dimensional
data however all objects appear to be sparse and dissimilar in many ways which
prevents common data organization strategies from being efficient.  The term
curse of dimensionality was coined by Richard E. Bellman when considering
problems in dynamic optimization.

* What is a Cox model
A quick introduction to Cox models can be found [[http://www.medicine.ox.ac.uk/bandolier/painres/download/whatis/cox_model.pdf][here]].
- A Cox model is a statistical technique for exploring the relationship between
  the survival of a patient and several explanatory variables.
- Survival analysis is concerned with studying the time between entry to a study
  and a subsequent event (such as death).
- A Cox model provides an estimate of the treatment effect on survival after
  adjustment for other explanatory variables. In addition, it allows us to
  estimate the hazard (or risk) of death for an individual, given their
  prognostic variables.
- A Cox model must be fitted using an appropriate computer program (such as SAS,
  STATA or SPSS). The final model from a Cox regression analysis will yield an
  equation for the hazard as a function of several explanatory variables.
- Interpreting the Cox model involves examining the coefficients for each
  explanatory variable. A positive regression coefficient for an explanatory
  variable means that the hazard is higher, and thus the prognosis
  worse. Conversely, a negative regression coefficient implies a better
  prognosis for patients with higher values of that variable.

* How science goes wrong (The Economist)
Link [[http://www.economist.com/news/leaders/21588069-scientific-research-has-changed-world-now-it-needs-change-itself-how-science-goes-wrong][here]].

A simple idea underpins science: "trust, but verify". Results should
always be subject to challenge from experiment. That simple but powerful idea
has generated a vast body of knowledge. Since its birth in the 17th century,
modern science has changed the world beyond recognition, and overwhelmingly for
the better.

* The truth wears off (The New Yorker)
Link [[http://www.newyorker.com/magazine/2010/12/13/the-truth-wears-off][here]].

On September 18, 2007, a few dozen neuroscientists, psychiatrists, and
drug-company executives gathered in a hotel conference room in Brussels to hear
some startling news.  It had to do with a class of drugs known as atypical or
second-generation antipsychotics, which came on the market in the early
nineties.  The drugs, sold under brand names such as Abilify, Seroquel, and
Zyprexa, had been tested on schizophrenics in several large clinical trials, all
of which had demonstrated a dramatic decrease in the subjects' psychiatric
symptoms.  As a result, second-generation antipsychotics had become one of the
fastest-growing and most profitable pharmaceutical classes.  By 2001, Eli
Lilly's Zyprexa was generating more revenue than Prozac.  It remains the
company's top-selling drug.

* Genomic instability is not seen on non-solid tumours
The fabric of cancer biology---weaving together the strands

It is worth pointing out that the exceptions to this general description of
cancer as a "disease of genetic instability" are the cancers, generally
noncarcinomas, that possess single, reproducible balanced translocations of
specific chromosomal sites (i.e., leukemias, some lymphomas, Ewing's
sarcoma). In these cases, there is no evidence of any underlying state of
genomic instability.

* Methods section

** For the microarray subsection
Follow this structure:
http://www.healthtech.com/2002/mda/index.htm
