#+STARTUP: indent
#+STARTUP: overview
#+LaTeX_HEADER: \documentclass{article}
#+LaTeX_HEADER: \usepackage[T1]{fontenc}
#+LaTeX_HEADER: \usepackage{mathptmx}
#+LaTeX_HEADER: \usepackage[scaled=.90]{helvet}
#+LaTeX_HEADER: \usepackage{courier}
#+TITLE:     Differentiation and Proliferation in Cancer
#+AUTHOR:    Gil Tomás
#+EMAIL:     gil.tms@gmail.com
#+DATE:      2013-04-01 Mon
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:
#+LINK_HOME:

* Introduction
** life
A brief recapitulation on the canonical perspective of the evolutionary history of life. From unicellular to multicellular organisms. Focus on the concepts of evolution and adaptation, homeostasis (homeodynamics), high level structural tissular integration, response to stimuli and cell-to-cell communication.

This section of the introduction will provide the reader with some of the core concepts around which the discussion will be framed.
** cancer
*** cancer: as an exception to the order of life
Cancer is first introduced as a fundamental disruption of homeostatic processes and a consequence of the complexity of biological systems. Inasmuch, a first conceptual argument is made for the better understanding of life through a more thorough comprehension of cancer as a failure to sustain homeostatic equilibrium in an organisms.
using a better understanding cancer as a way of better understanding life.
*** cancer: a clinical perspective
Cancer is one
**** incidence of cancers
A global analysis of the most recent WHO cancer incidence data is presented here.
*** The biology of cancer

*** dedifferentiation in cancer
*** proliferation in cancer
** microarrays
** goals of the thesis
* Material and methods
* Results
* Disscussion
